version: '3'

services:
  # TODO: auto build script/command, check CORS
  golang:
    image: golang:1.8
    tty: true
    ports:
      - ${API_HOST_HTTP_PORT}:80
    volumes:
      - ./backend:/go/src/app
    working_dir: /go/src/app
    depends_on:
      - cassandra
    networks: 
      - backend

  # TODO: username password seeds broadcast args
  cassandra:
    image: cassandra:3.11.1
    ports:
      - ${CASSANDRA_SYNC_PORT}:7000
    volumes:
      - cassandra-storage:/var/lib/cassandra
    networks: 
      - backend

  # TODO: api url, react
  react:
    image: sinet/nginx-node:latest
    volumes:
      - ./docker/nginx/sites:/etc/nginx/conf.d
      - ./frontend:/var/www/app
    working_dir: /var/www/app
    ports:
      - ${HOST_HTTP_PORT}:80
      - ${HOST_HTTPS_PORT}:443
    networks: 
      - frontend

volumes:
  cassandra-storage:
networks:
  backend:
  frontend: